In [1]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print("Original array:\n",a)

Original array:
 [[1 2 3]
 [4 5 6]]


In [3]:
b=[[0,1,2,3],[4,5,6,7]]
print("\n Element at indices(0,3),(1,2),(2,1),""(3,0):\n",b)


 Element at indices(0,3),(1,2),(2,1),(3,0):
 [[0, 1, 2, 3], [4, 5, 6, 7]]


In [9]:
c=np.array([0,1,2,3,4])
d=c>1
e=c[d]
print (e)

[2 3 4]


In [12]:
f=np.array([1,2,3,4,5,6,7,8,9,10])
print("\n Returns every other elememts in the array:f[::2]:",f[::2])


 Returns every other elememts in the array:f[::2]: [1 3 5 7 9]


In [13]:
g=np.array([0,1,2])
h=np.array([11,12,20])
i=np.concatenate((g,h))
print("\n Joined array:\n",i)


 Joined array:
 [ 0  1  2 11 12 20]


In [14]:
i=np.hstack((g,h))
print("\n Horizontal joining:\n",i)


 Horizontal joining:
 [ 0  1  2 11 12 20]


In [15]:
i=np.vstack((g,h))
print("\n Vertical Joining:\n",i)


 Vertical Joining:
 [[ 0  1  2]
 [11 12 20]]


In [16]:
i=np.dstack((g,h))
print(i)

[[[ 0 11]
  [ 1 12]
  [ 2 20]]]


In [17]:
j=np.array_split(f,3)
print(j)

[array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]


In [18]:
print(j[0])
print(j[1])
print(j[2])

[1 2 3 4]
[5 6 7]
[ 8  9 10]


In [19]:
k=np.array([1,4,3,4,7,4,12,4,6,4])
l=np.where(k==4)
print(l)

(array([1, 3, 5, 7, 9], dtype=int64),)


In [20]:
m=np.where(k%2==0)
print(m)

(array([1, 3, 5, 6, 7, 8, 9], dtype=int64),)


In [21]:
n=np.searchsorted(k,3,side='left')
print(n)

1


In [22]:
p=np.sort(k)
print(p)

[ 1  3  4  4  4  4  4  6  7 12]


In [23]:
q=np.array([71,72,73,74])
y=[True,False,True,False]
z=q[y]
print(z)

[71 73]


In [24]:
a1=np.array([1,2,3,4,5])
b1=np.array([6,7,8,9,10])
print(a1+b1)

[ 7  9 11 13 15]


In [25]:
print(a1-b1)

[-5 -5 -5 -5 -5]


In [26]:
print(a1*b1)

[ 6 14 24 36 50]


In [27]:
print(a1/b1)

[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [28]:
print(a1.dot(b1))

130


In [29]:
sclr=5
print(a*sclr)

[[ 5 10 15]
 [20 25 30]]


In [33]:
def my_func(x,y):
    if x>y:
        return x-y
    else:
        return x+y
c1=np.array([10,4,20])
d1=np.array([2,3,30])
vec_func=np.vectorize(my_func)
print(vec_func(c1,d1))

[ 8  1 50]
