In [1]:
import numpy as np
arr=np.array([[1,2,3,4],
              [5,6,7,8],
              [1,2,3,4]])
print("\n Size of array:",arr.size)


 Size of array: 12


In [2]:
print("\n Array stors elements of type:",arr.dtype)


 Array stors elements of type: int32


In [3]:
a=arr.astype('f')
print("\n Converted array element:\n",a)
print("Converted array type:",a.dtype)


 Converted array element:
 [[1. 2. 3. 4.]
 [5. 6. 7. 8.]
 [1. 2. 3. 4.]]
Converted array type: float32


In [7]:
b=np.empty((8,4))
for i in range(8):
    b[i]=i
print (b)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [9]:
print(b[[4,3,0,6]])

[[4. 4. 4. 4.]
 [3. 3. 3. 3.]
 [0. 0. 0. 0.]
 [6. 6. 6. 6.]]


In [10]:
print(b[[-3,-5,-4]])

[[5. 5. 5. 5.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]


In [15]:
c=np.arange(15).reshape((3,5))
print(c)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [16]:
print(c.shape)

(3, 5)


In [17]:
print(c.T)

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [18]:
print(c.T.shape)

(5, 3)


In [ ]:
print("Every alternate")